### PR TITLE
fixed region for retrieving frontend env secret

### LINKED ISSUE #13: Migrate frontend/.env secrets over to us-east-1
# Problem
Currently, we store our secrets that we populate in `frontend/.env` to AWS Secrets Manager in `us-west-2` region. However, DLP is migrating to `us-east-1` as the region for its AWS services to keep resources closer to where most of the team is based (which is in Atlanta area). 

# Solution
This task focuses on migrating the `frontend/.env` secrets to AWS Secrets manager in `us-east-1` region. The `frontend/.env` secrets in AWS Secrets manager have already been copied over to `us-east-1` region, but we need to update the `dlp-cli` to reflect that the AWS region being used is `us-east-1` along with testing that the `build_frontend_env` command is fetching the secrets correctly. 

# Step By Step
- [X] Copy over the `frontend/.env` secrets from `us-west-2` to `us-east-1` on the side of AWS Secrets Manager 
- [x] Ensure that Go is installed ([link](https://go.dev/doc/install))
- [x] Update the `dlp-cli` to retrieve the frontend env secrets from `us-east-1` instead of `us-west-2`. Might want to peek at the `dlp-cli/cmd/frontend` directory
- [x] Test that the `build_frontend_env` command in `dlp-cli` works by running `go run main.go frontend build-frontend-env-file --secret "frontend_env"`
- [ ] Create PR. Post in #prs channel in DLP Discord. Tag @Project Lead
- [ ] Once the PR is merged, create a tag named something like `v0.3.0` for example (use this [link](https://semver.org/) to make your best judgement). You can do this by going [here](https://github.com/DSGT-DLP/dlp-cli/releases) and clicking "Draft a New Release". If you are absolutely stuck on how to name the tag, please message in the DLP discord (in the #backend channel). We can help provide some ideas/insight here
- [ ] Once the tag is created, the `goreleaser` github action is run which automatically updates our `brew` and `scoop` packages for `dlp-cli`
- [ ] Post a message in #general channel of DLP discord along the lines of 
"We have pushed an update to the build_frontend_env file command. Please upgrade your DLP cli by running `brew upgrade dlp-cli` if MacOS/Linux or `scoop update scoop-dlp-cli/dlp-cli` if Windows". You can see a sample message [here](https://discord.com/channels/978856797190369341/978856797190369344/1190037941238628422)

### PR DESCRIPTION
**Pull request by sliu526**
Fixed region for retrieving frontend env secret (from us-west-2 to us-east-1).

GitHub issue described [here](https://github.com/DSGT-DLP/dlp-cli/issues/13).

**Process**

1. Changed region in frontend.go file in dlp-cli --> cmd --> frontend from us-west-2 to us-east-1
2. Tested that the build_frontend_env command in dlp-cli works by running `go run main.go frontend build-frontend-env-file --secret "frontend_env"`
3. Encountered error messages detailed and solved in [this link](https://www.notion.so/9b6766cea0b24060bb10d806d58ee0c1?v=1c2cddea700a478a86e95a5e86c09cf8&p=66c7901f9780469ebde4d0cd669dfc87&pm=s).
4. Added fix in build-frontend-env-file to parse through key:value secret values and updated .env file
5. Tested with go script from step 2

### CODE REVIEW

**Review by farisdurrani — DISMISSED** [review]

**Review by codingwithsurya — DISMISSED** [review]
LGTM!

File: cmd/frontend/build_frontend_env/build-frontend-env-file.go [hunk 1]
```diff
@@ -13,6 +13,7 @@ import (
     "github.com/spf13/cobra"
     "github.com/DSGT-DLP/Deep-Learning-Playground/cli/cmd/frontend" // For frontend/
     "github.com/DSGT-DLP/Deep-Learning-Playground/cli/utils" // For utils/
+    "encoding/json" // to unmarshal json
```
Comment (karkir0003) [inline cmd/frontend/build_frontend_env/build-frontend-env-file.go]: i dont think you need the // to unmarshall json comment. its a bit redundant bc your implementation explains this

File: cmd/frontend/build_frontend_env/build-frontend-env-file.go [hunk 2]
```diff
@@ -33,9 +34,18 @@ var buildFrontendEnvCmd = &cobra.Command{
         }
 
         path := "./frontend"
+        
+        // AWS secrets are parsed from key:value pairs in secrets manager for populating the .env file
 
-        // Adding secrets to the .env file
-        utils.WriteToEnvFile(secretName, *secretValue.SecretString, path)
+        var secretsMap map[string]string // declares a variable of type Map with key:value as string:string
```
Comment (karkir0003) [inline cmd/frontend/build_frontend_env/build-frontend-env-file.go]: this comment is unnecessary bc this line of code is self explanatory

File: cmd/frontend/build_frontend_env/build-frontend-env-file.go [hunk 3]
```diff
@@ -33,9 +34,18 @@ var buildFrontendEnvCmd = &cobra.Command{
...
+
+        if err := json.Unmarshal([]byte(*secretValue.SecretString), &secretsMap); err != nil { // stores unmarshalled json into secretsMap
```
Comment (karkir0003) [inline cmd/frontend/build_frontend_env/build-frontend-env-file.go]: you can remove the // stores unmarshalled json into secretsMap comment

**Review by karkir0003 — CHANGES_REQUESTED** [review]
minor changes

**Review by karkir0003 — APPROVED** [review]
LGTM @sliu526
